language: node_js
node_js:
- '4'
script:
- npm run build
after_success:
- npm install -g firebase-tools
- 'if [[ "${TRAVIS_BRANCH}" == "master" ]]; then firebase deploy; fi'
env:
  global:
    secure: iFul4u0RBL8mUe5p5mgADYE+b2oUUb/xH4A7LEtVlU8c9gqKbBS3XnptNjNMVpKgyLnfstDH93tW/jw8C4lZ6s5pSq8yMBoESllkfVnqMXPeh9UWRD49EG0PSl8L5C2r6CsNds2IioooloAY95IVNnPjO+gUW9eTKWE120nKy1ZnipwNX3yivQJ0n0hUYlYnaOHC0BI7JMJzS70Q5palt5425IK72+unqxeRZE3VSZ/n85f59myFKsUrQE1lHJhGlBVfh8G1ba/P5GBkzxWfOtgJ/GErViRPB6zTpQoxxjeRp/VWFUwItYBx2jwxHu/ma+N2ckoD3BwObxMNIYfdjCnKjWeUnUxV4Dcc6Nkdv71kuaRD/tgSagJh9j/1cuHn6n3ja2QVckz9dOQ5oEC8V3xJDDYzmjjwa8ROQ+FSCDfs864wAT9HmiT1pyPiATpXQFfQfwWhv1JG2mxEHeQy3fVWEtL0+0HxOqZj3TqMtPkb+hX+Vs8fFYpY19sxRw37meS/NzJqyBX2AaY49KzkVMa5/PJSlwJfKSg6zaWTub/e32OALOqHjE90npnzNG6GRhQUlq9bFqmd1HQ+BjexpQS8PK+EGyetS8D+a+JKEVdRIQB7qjkCp8sU2ztQq3ikJISNJnkNIDS2PSNJbZEjm4Fl/ktdmQMMF9kZM4yyRCQ=
